baseURL = 'https://paper-abbey.vercel.app/'
languageCode = 'en-us'
title = 'Paper Abbey'
theme = 'paper'

disqusShortname = 'paper-abbey'   # add disqus comments

[params]
  # color style
  color = 'linen'                 # linen, wheat, gray, light

  # header social icons
  twitter = 'vinchibana'     # twitter.com/YOUR_TWITTER_ID
  github = 'vinchibana'       # github.com/YOUR_GITHUB_ID
  instagram = 'vialin1128' # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                      # show rss icon with link

  # home page profile
  avatar = 'https://s2.loli.net/2022/09/23/J4YrQbyTgRq9GUd.jpg'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
  name = '鹊桥仙仙'
  bio = 'Fais ce que tu voudras'

  # misc
  disableHLJS = true              # disable requesting highlight.js
  monoDarkIcon = true             # show monochrome dark mode icon
